version: '3'

services:
  dev:
    image: golang:1.18
    working_dir: /source
    command: >
      sh -c "go install github.com/unchartedsoftware/witch;
             witch --cmd=\"find . -name go.mod -execdir go test -v ./... '\;'\" --watch=\"*.mod,**/*.go\""
    environment:
      PHOENIX_HOST: http://phoenix:8765
      MYSQL_HOST: mysql:3306
      POSTGRES_HOST: postgres:5432
    volumes:
      - .:/source
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    depends_on:
      - mysql
      - phoenix
      - postgres

  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phoenix:
    image: boostport/hbase-phoenix-all-in-one:2.0-5.0

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  lint:
    image: golang:1.18
    working_dir: /source
    command: >
      sh -c "go install github.com/golangci/golangci-lint/cmd/golangci-lint;
             make sanity-check"
    volumes:
      - .:/source
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache