version: '3'

services:
  dev:
    image: golang:1.16-alpine
    working_dir: /source
    command: >
      sh -c "apk --no-cache --no-progress add gcc git musl-dev;
             go install github.com/unchartedsoftware/witch;
             witch --cmd=\"go test -v -p 1 ./...\" --watch=\"*.mod,**/*.go\""
    environment:
      PHOENIX_HOST: http://phoenix:8765
      MYSQL_HOST: mysql:3306
      POSTGRES_HOST: postgres:5432
    volumes:
      - .:/source
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    depends_on:
      - mysql
      - phoenix
      - postgres

  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  phoenix:
    image: boostport/hbase-phoenix-all-in-one:2.0-5.0

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  lint:
    image: golang:1.16-alpine
    working_dir: /source
    command: >
      sh -c "apk --no-cache --no-progress add gcc git make musl-dev;
             go install github.com/golangci/golangci-lint/cmd/golangci-lint;
             make sanity-check"
    volumes:
      - .:/source
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache

  update-test-bindata:
    image: golang:1.16-alpine
    working_dir: /source
    command: >
      sh -c "apk --no-cache --no-progress add gcc git musl-dev;
             go install github.com/go-bindata/go-bindata/v3/go-bindata;
             go-bindata -o bindata_test.go -pkg migration test-migrations/;
             echo \"go-bindata test data generated.\""
    volumes:
      - .:/source
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache