on: [push, pull_request]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go:
          - version: 1.16
            report: true
          - version: 1.15
    runs-on: ubuntu-latest
    container:
      image: golang:${{ matrix.go.version }}
    services:
      phoenix:
        image: boostport/hbase-phoenix-all-in-one:2.0-5.0

      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        options: --health-cmd "while ! mysql -e \"select 1\" -uroot >/dev/null 2>&1; do sleep 1; done" --health-interval 10s --health-timeout 5s --health-retries 5

      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install code climate
        if: matrix.go.report == true && github.ref == 'refs/heads/master'
        run: |
          wget -O /tmp/cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
          chmod +x /tmp/cc-test-reporter
          /tmp/cc-test-reporter before-build
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint checks
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install github.com/golangci/golangci-lint/cmd/golangci-lint
          make sanity-check
      - name: Run tests
        env:
          PHOENIX_HOST: http://phoenix:8765
          MYSQL_HOST: mysql:3306
          POSTGRES_HOST: postgres:5432
        run: |
          go test -coverprofile c.out -v ./...
          echo $? > /tmp/GO_EXIT_CODE
      - name: Send results to code climate
        if: matrix.go.report == true && github.ref == 'refs/heads/master'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          /tmp/cc-test-reporter after-build --prefix github.com/$GITHUB_REPOSITORY --exit-code `cat /tmp/GO_EXIT_CODE`